### ISSUE TITLE
Maximum password length is 32 characters

### ISSUE THREAD

**Issue by loops** [timvisee/ffsend#10]
Hi, thanks for the great utility.

The automatically generated password with -P on my system is 5 words and often is longer than the maximum allowed password length of 32 characters.  This means that the download is unavailable.

**Comment by timvisee** [comment]
Thank you.

Interesting. Mabye the 32-character limit is new in the Firefox Send version that has just been released.

I'll take a look into it soon. Thank you for the report.

**Comment by timvisee** [comment]
This issue has been fixed in `v0.2.29`.

`ffsend` is using a list with shorter words now, the [EFF general short](https://gitlab.com/timvisee/chbs/blob/master/res/eff/general_short.txt) list to be exact. As this list contains less words entropy decreases slightly, but that should be all right. The set of words are 5 characters long at max, allowing a maximum password length of 29 characters (including the spaces).

The new version should be available as soon as the following release pipeline succeeds:  
https://gitlab.com/timvisee/ffsend/pipelines/51519657
