### ISSUE TITLE
Request for web REST API

### ISSUE THREAD

**Issue by unl1k3ly** [timvisee/ffsend#101]
Awesome project ! 

Well done mate! 

If i can ask you something, would be possible to wrap it all up in a Web API ? 

Cheers

**Comment by timvisee** [comment]
@unl1k3ly What do you mean exactly with a web API?

Would you like to have a HTTP REST like interface to manage files? Maybe the endpoints provided by Send are already sufficient enough?

Thanks!

**Comment by unl1k3ly** [comment]
Thanks for replying.

Yes, like a REST. I tried to look for any documentation around Send but i
did not find it anything unless digging into the app itself.

Cheers

**Comment by timvisee** [comment]
The endpoints Send provides aren't really documented, nor are they intended to be used as public API. So you're right, there isn't much to find on it other than inspecting the source code.

`ffsend` does not provide a REST interface at this moment. I did split this library up into `ffsend` and `ffsend-api`, in which the latter provides a client to easily communicate with a Send instance. If you're familiar with Rust, you might be able to build a REST server around this `ffsend-api` client crate to suit your needs.

I do not intent to develop a REST interface any time soon for Send. Primarily because I've very limited time available, and also because I don't really think it would be of too much use.

Could you elaborate why you'd like to have REST interface? That might help me understand this request better, or I might be able to point you in a better direction. If you'd just like to have your own interface, you may just host a Send instance yourself and modify that.

Thinking of it, I do want to point out that providing a REST interface could make Send less secure. Either the REST clients would have to implement their own client-side encryption to crypt uploaded/downloaded files (this wouldn't really follow the REST rules). Or these files would have to be crypted on the REST server, to send files in plain-text through this REST interface. The latter basically breaks end-to-end encryption and it would allow the server to snoop files and to initiate a [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) attack.

**Comment by unl1k3ly** [comment]
We do have some automation in-house where we use SEND as a deliverer once
the file touch our endpoint. Right now, are only using SEND 2.0.0 which is
a bit old but it works! SEND is just easy to deal with and it has a decent
UI,

But yea, unfortunately API isn't as great in SEND side.

I've asked about a REST because I'm likely to code an API around your
binary which isn't necessary a bad thing but its not a good coding
practices neither doing an API round sub system calls.

Thanks for all your help and neat work mate.

**Comment by timvisee** [comment]
I see. Sound like a nice application.

In the mean time, maybe you're able to do this using this `ffsend` by invoking a command from your system. Just invoke something like

```bash
ffsend upload -Iyfq MY_FILE
```

and it will return the share URL for you. This isn't REST, but maybe it's something you can use. See [Scriptability](https://github.com/timvisee/ffsend/#scriptability).

If you just want to upload a file through a REST interface, I might be able to to set up a simple binary providing an endpoint for this tomorrow, as it shouldn't be too much work.

**Comment by unl1k3ly** [comment]
Thank you!
