### ISSUE TITLE
"path is not an existing file" when using snap package

### ISSUE THREAD

**Issue by tmalsburg** [timvisee/ffsend#12]
I installed the snap on the current Ubuntu LTS and get the following error message when I try uploading a file:

```
$ ffsend upload test.org
error: failed to check the file size, ignoring
error: failed to upload the specified file
caused by: the given path is not an existing file

For detailed errors try '--verbose'
For more information try '--help'
```

The file definitely exists.  Also, adding `--verbose` doesn't produce additional information.  I'm probably missing something obvious?

**Comment by timvisee** [comment]
Thank you for the report.

Currently the `snap` package is limited to accessing files in your home directory, as the `snap` is isolated (as configured [here](https://github.com/timvisee/ffsend/blob/bd034a40d9bb7bea8e7e8a0ffe209594ff35e805/pkg/snap/snapcraft.yaml#L26) if you're wondering). Because of this, `ffsend` just can't find the file as it's invisible.

If you prefer to access files outside your home directory as well, you must choose a different installation option (that is not the `snap` package).

I might improve the error message produced in these situations though, to make it better understandable. I'll add a note for this limitation in the README as well.

**Comment by tmalsburg** [comment]
Thanks for the quick response.  It works in my home directory.  For me it was fairly unexpected that it only works in certain directories.  Command line tools usually don't behave that way.  What speaks against lifting this restriction?

**Comment by timvisee** [comment]
> Thanks for the quick response. It works in my home directory. For me it was fairly unexpected that it only works in certain directories. Command line tools usually don't behave that way. What speaks against lifting this restriction?

Yes, you're right. The _problem_ here is that `snap` is designed to be isolated by default, to make it more secure. I believe the idea is that you can't peek into (or change) into system files and such, to make it impossible for snapped software to destroy your system.

Anyway. I don't think `snap` has a property to allow full filesystem access. I'll take a look into it, and will close the issue for now. If I find a method for enabling full filesystem access, I'll enable that for sure.

**Comment by tmalsburg** [comment]
Having some safeguards of that type may actually make sense.  Just something to get used to.  If there is a possibility to add `/tmp` to the list of allowed paths, it would be useful to include it.  `/tmp` should be fairly save.

**Comment by timvisee** [comment]
I did come across this plug/interface: [`system-files`](https://docs.snapcraft.io/the-system-files-interface/9358) ([full list](https://docs.snapcraft.io/supported-interfaces/7744)).  
But I don't think this provides access to `/tmp` and other non-system directories.

**Comment by Lin-Buo-Ren** [comment]
Snap packager passing by, in addition to "regular" files under your home directory("regular" means not including hidden files right under your `$HOME`) you can also access files under `/mnt` and `/media` if you connect the `removable-media` interface via running the `sudo snap connect ffsend:removable-media` command.

For most use cases these accesses should suffice, it should be very fewer people who store large files under `/tmp` which is usually volatile between boots.

**Comment by Lin-Buo-Ren** [comment]
> I did come across this plug/interface: [`system-files`](https://docs.snapcraft.io/the-system-files-interface/9358) ([full list](https://docs.snapcraft.io/supported-interfaces/7744)).  
> But I don't think this provides access to `/tmp` and other non-system directories.

Even if it does it won't have access to the actual `/tmp` directory as all snaps have their own temp folders.  The only feasible way is to make it classic confinement, which probably won't be allowed to publish to the Snap Store as it's not really a hard requirement.

**Comment by timvisee** [comment]
@Lin-Buo-Ren Thank you for the heads up!

Currently, the snap package ships with `removable-media` by default: https://github.com/timvisee/ffsend/blob/c068e4c1433551e4292376547b9256049963ef5d/pkg/snap/snapcraft.yaml#L26

Snapcraft rejects the classic confinement now, so that's not an option.

So, that leaves us with no other option than to report to the end user a file system entry may be hidden if running `ffsend` as snap package.

I've created the following issue for it over on GitLab:
https://gitlab.com/timvisee/ffsend/issues/66
