### ISSUE TITLE
Always fails on FreeBSD

### ISSUE THREAD

**Issue by sryze** [timvisee/ffsend#121]
Hello,

I'm using ffsend on a FreeBSD machine on Travis CI and it seems to always fail with the same error:

```
$ ffsend --verbose upload <my_file_here>
error: failed to upload the specified file
caused by: failed to upload the file
```

Same happens in my VirtualBox VM.

However, it doesn't produce any error on Linux, Windows and macOS, so I suspect it is something specific to FreeBSD. 

Do you have idea why it would fail?

**Comment by timvisee** [comment]
Are you running `v0.2.65` (run `ffsend -V`)?

**Comment by sryze** [comment]
0.2.64

I installed it with pkg

**Comment by timvisee** [comment]
Sadly, all versions prior to `v0.2.65` are currently broken. That is because Mozilla took their public Send instance down, which was used by `ffsend`. Version `v0.2.65` uses a different Send instance by default, which is hosted by me.

See this issue for more details on this:  
https://gitlab.com/timvisee/ffsend/-/issues/101

The FreeBSD package is maintained by FreeBSD contributors. So I can't easily publish a new version there at this moment, though I'll take a look into it.

I think you have two options for now:
- Select a different Send host to use.
- Use `v0.2.65`, which you probably have to compile from source.

For the first option, you may set the `--host` flag or the `FFSEND_HOST` environment variable:

```bash
# Set environment variable
export FFSEND_HOST="https://send.vis.ee"

# OR explicitly provide host parameter
ffsend upload --host "https://send.vis.ee" FILE
```

**Comment by sryze** [comment]
OK, thanks!
