### ISSUE TITLE
Default expiry-time and download limit

### ISSUE THREAD

**Issue by albertopasqualetto** [timvisee/ffsend#124]
Is it possible to set the default expiry-time and download limit?

**Comment by albertopasqualetto** [comment]
I think the problem is that I don't know how to use them.

**Comment by timvisee** [comment]
What platform are you on? You're likely able to set them globally or in your shell.

Please note that a variable to set the default expiration time is currently not available. I was only asking whether such variable would be useful if I'd add it. Because that could be a simple solution for your question.

**Comment by albertopasqualetto** [comment]
Ok, I understand. I am on Windows

**Comment by timvisee** [comment]
I've added the `FFSEND_EXPIRY_TIME` environment variable to set the _default_ expiration time, this is now available in `ffsend` `v0.2.70`.

You could set a user environment variable with this name and the desired number of seconds.

This might be useful: https://www.alphr.com/environment-variables-windows-10/

**Comment by anishmittal2020** [comment]
@timvisee  Is it possible to set default download limit with an environment variable? It seems to be 1 by default.
