### ISSUE TITLE
Scoop release almost a year out of date

### ISSUE THREAD

**Issue by t3dium** [timvisee/ffsend#158]
![ApplicationFrameHost_MRBlldgijB](https://user-images.githubusercontent.com/83690012/236798321-deac5de0-18a7-4f54-9825-e68a4e2f648c.png)

From the main bucket, the ffsend version is release 0.2.73 rather than the latest 0.2.76

**Comment by YDX-2147483647** [comment]
I guess there's something wrong in the release process. If you download v0.2.76 then `./ffsend-v0.2.76-windows-x64-static.exe --version`, it's still `ffsend 0.2.73`. Moreover, the files are identical!

```shell
> sha256sum .\ffsend-*
09d923348d083c130e8e26f990ba4c90022a2b26e6a9f0c55ac78420f84089f8 *ffsend-v0.2.73-windows-x64-static.exe
09d923348d083c130e8e26f990ba4c90022a2b26e6a9f0c55ac78420f84089f8 *ffsend-v0.2.76-windows-x64-static.exe
```

The hash is the same as in https://github.com/ScoopInstaller/Main/blob/4fffebe4058f2ee7a0cb9ac90c2574f1722774e8/bucket/ffsend.json, so that scoop won't update it.
