### ISSUE TITLE
failed to upload the specified file

### ISSUE THREAD

**Issue by yshinkarev** [timvisee/ffsend#20]
Kubuntu 18.04 amd64.
ffsend-v0.2.30-linux-x64-static

`$ ffsend.sh upload 1MB --download-limit 2 --timeout 3600 --copy --verbose`

> Upload complete                                                                                                                              error: failed to upload the specified file
> caused by: failed to change file parameters
> caused by: failed to send the parameter change request
> caused by: bad response from server while changing parameters
> caused by: bad HTTP response: 400 Bad Request
>

**Comment by timvisee** [comment]
Related to: https://github.com/timvisee/ffsend/issues/17

Thank you for the report.

Currently the public [Firefox Send](https://send.firefox.com/) instance only supports a limit of `1` download per file for non-authenticated users. The server rejects more downloads, which is why the `400` error is given.

I'll implement support for Firefox Account authentication soon, which is a priority right now. And I'll also improve the error message that you've mentioned to make it better understandable.

**Comment by timvisee** [comment]
Support for Firefox Accounts, supporting higher download/expiry limits, is currently tracked in the following issue, over on GitLab:
https://gitlab.com/timvisee/ffsend/issues/58

Be sure to subscribe on it to stay up-to-date.
