### ISSUE TITLE
Install with Homebrew

### ISSUE THREAD

**Issue by Cronos87** [timvisee/ffsend#21]
Hello,

It would be really great if macOS users can install it via Homebrew.

Will it be added in the nearest future?

Thank you.

**Comment by timvisee** [comment]
I agree, I would love to have a `homebrew` package. But I can't say when it's ready.

I'm not familiar with homebrew though, and don't know much more than it being a 'package manager' for macOS. I did take a look at the homebrew documentation but didn't fully understand how to define a package yet, and gave up soon afterwards because there were some other things I had to complete. It is still one of the highest priority things to build for `ffsend` though.

If you're familiar with configuring homebrew packages, it would be awesome if you could make a head start!

**Comment by Cronos87** [comment]
I really want to play with your package as soon as possible :)
I'll try to do it for you this week and come back to you when it's done.

Thank you for your answer!

**Comment by timvisee** [comment]
> I really want to play with your package as soon as possible :)
> I'll try to do it for you this week and come back to you when it's done.
> 
> Thank you for your answer!

Cool!

I'd like to note that if you just want to give `ffsend` a try, you can take a look at the [prebuilt binary for macOS](https://github.com/timvisee/ffsend#macos-prebuilt-binaries).

**Comment by Cronos87** [comment]
Yes, indeed. But I will focus on the Homebrew package first ;)

**Comment by matevzmihalic** [comment]
I've created the formula and opened PR for ffsend in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/37906

**Comment by Cronos87** [comment]
haha I finished it and wanted to publish it this evening, but well done. Thank you @matevzmihalic 👍

**Comment by timvisee** [comment]
@matevzmihalic You're awesome!

Could you constrain the `openssl` dependency to use `1.1` by configuring it as `openssl@1.1`?

Also, how do I go about updating this. I prefer to automate everything, especially for releases. Do I have to push a pull request every time a new update is released just to update the formula? I'm sorry, not familiar with `homebrew`.

**Comment by matevzmihalic** [comment]
You have to push a pull request for new release, but you can use [brew bump-formula-pr](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula) to help you with that.

Homebrew doesn't like binary packages, because they want to give their users an option to compile from source, but they provide binary packages by default (called bottles). Bottles get compiled automatically when the formula is merged and when someone writes `brew install ffsend` they will actually get precompiled binary.

I specified minimum rust version to `1.32`.

**Comment by timvisee** [comment]
Thanks for the explanation.

I'll probably implement `bump-formula-pr` into the CI pipeline at a later time.

I'll keep this issue open until the brew PR gets merged, after which I'll update the README.

**Comment by timvisee** [comment]
@matevzmihalic It might be good to add the `--force` flag as well for the `cargo install ...` command, to ensure `cargo` properly overwrites previous installations of `ffsend`.

**Comment by matevzmihalic** [comment]
@timvisee I don't think that's necessary, because it will install it in `prefix` path which includes version number (prefix for this package on my machine currently looks like `/usr/local/Cellar/ffsend/0.2.30`).

It will then automatically link the binary from that prefix to `PATH`

**Comment by timvisee** [comment]
The latest `ffsend` version (`v0.2.38`) is now available through `homebrew`. Hurray!
I've changed the [macOS installation instructions](https://github.com/timvisee/ffsend#macos-homebrew-package) accordingly.

Installing it is now as simple as:

```bash
# You might need to update your package index
brew update

# Install ffsend
brew install ffsend

ffsend --help
```

I'm currently in the process of automating these `homebrew` releases for each new version.
As a package is now available, I'll close this issue.
