### ISSUE TITLE
ffsend Windows version still is 0.2.39

### ISSUE THREAD

**Issue by DukeFox** [timvisee/ffsend#36]
![](https://i.loli.net/2019/04/03/5ca38ae1ab692.png)

**Comment by timvisee** [comment]
You're totally right.

I've had some issues with the automated release pipeline for Windows. Because of this, the last few releases failed to succeed. To make Windows downloads available for these on the GitHub releases page, I manually copied the last successful builds and uploaded those. The actual binary is indeed `v0.2.39` right now for all last few Windows versions. Since the last few versions didn't include changes that were significant enough, this isn't much of an issue and you don't have to worry about it.

Note that I've just solved the Windows release issue, which means that the next release should include a proper versioned binary for Windows.

I'll close this issue now. If you have any other questions, be sure to ask them.
