### ISSUE TITLE
Feature: Automatically generate random password/passphrase

### ISSUE THREAD

**Issue by brycx** [timvisee/ffsend#6]
Hi, great project!

I would love to see a feature added, that gives the user the option of either specifying a password for the file, or having ffsend generate one automatically. I think a 32 byte long random password would be nice for this. It could also be a passphrase instead, which would make them easier to share if this cannot be done per copy-paste and the receiving user has to manually type the password.

**Comment by timvisee** [comment]
Thank you.

It is already possible to set a password for a file that is uploaded. You can use the `-p` flag for this with the `upload` subcommand. See `ffsend help upload` for more information.

I like the idea of allowing to generate a random password based on some constraints. I'll leave this issue open for this functionality.

With Firefox Send itself it is not possible to integrate the password within the share URL, and that is a good thing! The idea of the the password is to add additional security so that bad people that somehow obtained the link are still not able to download the file. It is possible to add support to `ffsend` though for a feature like this, with the password appended in the URL, that password would only be automatically used within `ffsend`. I do not plan to implement this though because of the problem described above. Secondly, this would also allow a malicious Firefox Send server to steal the password from the URL when the share URL is used in the browser. The whole idea of such password is that it's only known on the client side, and the client side encrypts/decrypts the actual file, making it impossible for the server to see what file is uploaded even if the server might be malicious. I hope this is understandable, if not, be sure to let me know.

Note that this project is currently in heavy development. I'm currently working on properly releasing versions to easily install (and update). After that I'll continue on the actual coding work, and then I'll be able to implement this feature.

Also note that I'm in the process of moving the main repository to [GitLab](https://gitlab.com/timvisee/ffsend), after which this repository on GitHub will be a mirror. I might move this issue some time because of this.

Please let me know if you have any other questions or ideas.

**Comment by brycx** [comment]
> It is already possible to set a password manually for a file that is uploaded. You can use the -p flag for this with the upload subcommand. See ffsend help upload for more information.

Yes, the documentation on the current functionality is splendid!

> I believe you also suggested to allow having the password within the share URL, sorry if I misunderstood that.

This is not what I am suggesting. My suggestion is that instead of leaving it up to the users to generate a strong password/passphrase and set it themselves with the current `-p` flag, another flag could be added, lets call it `-p-gen`, which would generate a strong password/passphrase automatically, and return this to the user. Meaning: eliminating the part where the users have to specify a specific password.

**Comment by timvisee** [comment]
Affirmative! Thank you for clarifying.

The ability to generate a passphrase instead of a randomized string is a good call. Thank you.

I will keep this issue updated if I know anything on when I'll be implementing this.

**Comment by brycx** [comment]
No problem. Looking forward to see how this moves on.

**Comment by timvisee** [comment]
@brycx I've been working on a basic implementation, which is now available in the new `0.0.8` release (quicker than expected :smile:).

For generating a passphrase the `--gen-passphrase` (`-P`) flag can now be used while uploading or while setting the password after uploading. It is currently quite basic in the sense that the generated passphrases have a fixed length of 4 lowercase words using the wordlist [provided](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases) by EFF. Generated passphrases are reported in the console next to the share link.

I do want to further improve generating these phrases by allowing users to configure some constraints. Think of adding random numbers, special characters, capitalization, using a different number of words, requiring a certain entropy, using custom wordlists (of course, all common with these diceware passphrase generators). You can expect to see these features in a later release. I first wanted to do a quick release with basic functionality.

I started a new small crate for the actual password generation [here (crates.io)](https://crates.io/crates/chbs), and will work on improving password generation there.

The pull request can be found [here (GitLab)](https://gitlab.com/timvisee/ffsend/merge_requests/4).

Be sure to update your `ffsend`  installation to check it out! If it doesn't seem to be working, please verify that you've installed version `0.0.8 ` (or later) by invoking `ffsend -V`. If you've any thoughts on this, please let me know.

I'll leave this issue open until the other named passphrase generation constraints are implemented.

**Comment by brycx** [comment]
That was pretty quick. This looks promising, thanks @timvisee!

**Comment by timvisee** [comment]
I'll close the issue for now, as this feature is partially implemented.

Configurable passphrase generation is still something I want to implement in the future. I'll try to remember to notify this issue once work is started on it.
